<a href="https://colab.research.google.com/github/Anne-va/Linear-Algebra-58051/blob/main/Week%208/LinAlg_58051_System_of_Linear_Equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$ P = \left\{ \begin{array}\\ 7p+8a+3g=9\\ -6p-8a+4g=-3 \\ 1p+5a+4g=1 \end{array} \right. $$

In [1]:
import numpy as np

In [2]:
P = np.array([[7,8,3],
              [-6,-8,4],
              [1,5,4]
])

A = np.array([[9],
              [-3],
              [1],
])

print("Matrix P: \n", P)
print("\nMatrix A: \n", A)

P_inv = np.linalg.inv(P)
print("\nResults: ")
print(P_inv @ A)

Matrix P: 
 [[ 7  8  3]
 [-6 -8  4]
 [ 1  5  4]]

Matrix A: 
 [[ 9]
 [-3]
 [ 1]]

Results: 
[[ 1.75242718]
 [-0.63592233]
 [ 0.60679612]]


In [3]:
P_inv1 = np.linalg.solve(P,A)

print("Matrix P: \n", P)
print("\nMatrix A: \n", A)

print("\nResults: ")
print(P_inv1)

Matrix P: 
 [[ 7  8  3]
 [-6 -8  4]
 [ 1  5  4]]

Matrix A: 
 [[ 9]
 [-3]
 [ 1]]

Results: 
[[ 1.75242718]
 [-0.63592233]
 [ 0.60679612]]
