<a href="https://colab.research.google.com/github/Anne-va/Linear-Algebra-58051/blob/main/Week7/LinAlg_58051_Ebdane_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
matrix_1 = np.array([ [2, 4, 7],
                      [4, 9, 3],
                      [8, 9, 6],
                     ])
matrix_2 = np.array([ [5, 7, 8],
                      [3, 5, 9],
                      [6, 8, 2],
                     ]) 
matrix_3 = np.array([ [6, 2, 3],
                      [7, 4, 5],
                      [9, 8, 3],
                     ])
matrix_4 = np.array([ [3, 7, 9],
                      [4, 6, 8],
                      [3, 2, 6],
                     ])

In [24]:
def mat_desc(matrix):
  print(matrix)
  if matrix.size > 0:

    print("Shape: ", matrix.shape)
    print("Size: ", matrix.size)
    print("Rank: ", matrix.ndim)

    square = True if matrix.shape[0] == matrix.shape[1] else False 
    print("Is the matrix square? ", square)

    print("Is the matrix empy? NO")

    zeroes = not np.any(matrix)
    print("Is the matrix zeroes? ", zeroes)

    ones = np.all((matrix == 1))
    print("Is the matrix ones? ", ones)

    rows = len(matrix);
    colums = len(matrix[0]);
    identity = True
    for iteration in range(0, rows):
      for number in range (0, colums):
        if(iteration == number and matrix[iteration][number] !=1):
          identity = False
        if(iteration != number and matrix[iteration][number] !=0):
          identity = False

    if identity:
      print("Is the matrix identity? True")
    else:
      print("Is the matrix identity? False")

 
  else:
     print("Shape: N/A")
     print("Size: N/A")
     print("Rank: N/A")
     print("Is the matrix square? N/A")
     print("Is the matrix empty? YES")
     print("Is the matrix zero? N/A")
     print("Is the matrix ones? N/A")
     print("Is the matrix square? N/A")
     print("Is the matrix identity? N/A")

    
  

In [25]:
mat_desc(matrix_1)

[[2 4 7]
 [4 9 3]
 [8 9 6]]
Shape:  (3, 3)
Size:  9
Rank:  2
Is the matrix square?  True
Is the matrix empy? NO
Is the matrix zeroes?  False
Is the matrix ones?  False
Is the matrix identity? False


In [35]:
def mat_operations(P,E):
  print("First Matrix: \n", P)
  scalar_One = isinstance(P, (int, float, bytes, complex))
  print("Is the Matrix Scalar? \n", scalar_One)

  print("Second Matrix: \n", E)
  scalar_Two = isinstance(E, (int, float, bytes, complex))
  print("Is the Matrix Scalar? \n", scalar_Two)

  matrix_One = isinstance(P, np.ndarray)
  matrix_Two = isinstance(E, np.ndarray)

  if scalar_One == True or scalar_Two == True or matrix_One == True or matrix_Two == True and A.shape == B.shape:
    print("Addition: \n", P+E)
    print("Subtraction: \n", P-E)
    print("Multiplication: \n", P*E)
    print("Division: \n", P/E)
  elif matrix_Two == True and matrix_Two == True and A.shape!= B.shape:
    print("Operation cannot be performed, shape must be equal")


In [36]:
mat_operations(matrix_2, matrix_3)

First Matrix: 
 [[5 7 8]
 [3 5 9]
 [6 8 2]]
Is the Matrix Scalar? 
 False
Second Matrix: 
 [[6 2 3]
 [7 4 5]
 [9 8 3]]
Is the Matrix Scalar? 
 False
Addition: 
 [[11  9 11]
 [10  9 14]
 [15 16  5]]
Subtraction: 
 [[-1  5  5]
 [-4  1  4]
 [-3  0 -1]]
Multiplication: 
 [[30 14 24]
 [21 20 45]
 [54 64  6]]
Division: 
 [[0.83333333 3.5        2.66666667]
 [0.42857143 1.25       1.8       ]
 [0.66666667 1.         0.66666667]]
