<a href="https://colab.research.google.com/github/Anne-va/Linear-Algebra-58051/blob/main/Week8/LinAlg_58051_Ebdane_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
matrix_5 = np.array ([ [3, 8, 9],
                       [2, 7, 5],
                       [1, 9, 4],
                      ])
matrix_6 = np.array ([ [6, 7, 2],
                       [3, 6, 9],
                       [5, 9, 2],
                      ])
matrix_7 = np.array ([ [4, 9, 5],
                       [ 3, 2, 7],
                       [9, 5, 6],
                      ])


  **COMMUTATIVE PROPERTY**



$
AB \neq BA$

In [ ]:
AB = matrix_5 @ matrix_6
BA = matrix_6 @ matrix_5

print("AB = \n", AB)

print("AB = \n", BA)

 


 



AB = 
 [[ 87 150  96]
 [ 58 101  77]
 [ 53  97  91]]
AB = 
 [[ 34 115  97]
 [ 30 147  93]
 [ 35 121  98]]


 **ASSIOCIATIVE PROPERTY**

$(PE)A = B(EG)$

In [ ]:
PE_A = (matrix_5 @ matrix_6) @ matrix_7



In [ ]:
B_EG = matrix_5 @ (matrix_6 @ matrix_7)

In [ ]:
print("(PE)A: \n", PE_A)

(PE)A: 
 [[1662 1563 2061]
 [1228 1109 1459]
 [1322 1126 1490]]


In [ ]:
print("B(EG): \n", B_EG)

B(EG): 
 [[1662 1563 2061]
 [1228 1109 1459]
 [1322 1126 1490]]


In [ ]:
np.array_equiv(PE_A, B_EG)

True

**DISTRIBUTIVE PROPERTY**

$A(P+E) = AP+AE$

In [ ]:
A_PE = matrix_5 @ (matrix_6 + matrix_7) 
AP_AE = (matrix_5 @ matrix_6)+ (matrix_5 @ matrix_7)

In [ ]:
print("A(P+E): \n", A_PE)

A(P+E): 
 [[204 238 221]
 [132 158 166]
 [120 144 183]]


In [ ]:
print("AP+AE: \n", AP_AE)

AP+AE: 
 [[204 238 221]
 [132 158 166]
 [120 144 183]]


In [ ]:
np.array_equiv(A_PE, AP_AE)

True

**MULTIPLICATIVE IDENTITY PROPERTY**

$IP = P$

In [ ]:
I = np.eye(3, dtype = int)
IP = I @ matrix_5

In [ ]:
print("IP: \n", IP)

IP: 
 [[3 8 9]
 [2 7 5]
 [1 9 4]]


**TRANSPORSATION PROPERTY OF MULTIPLICATION**

$P\cdot P^{-1}= I$

---



In [9]:
matrix_5 = matrix_5 @ np.linalg.inv(matrix_5)
I_1 = np.eye(3, dtype= int)

In [11]:
print("A(A inv) = \n", matrix_5.astype(int))
print("I = \n", I_1)

A(A inv) = 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
I = 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [12]:
np.array_equal(matrix_5, I_1)

True

MULTIPLICATIVE PROPERTY OF ZERO

$P0=0$

In [13]:
import numpy as np 
zero = np.zeros(matrix_5.shape)
P_zero = matrix_5 @ zero

In [14]:
print("P0 = \n" , P_zero)
print("zero = \n", zero)

P0 = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
zero = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
